name: telegram message
on: [push]
jobs:
  notify:
    name: notify
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Repository: ${{ github.repository }}
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
